trigger: none

pool:
  name: 'Percapita'
  demands:
    - agent.name -equals ubuntu-build-agent

variables:
  - name: docker_aiservice_repo
    value: "ragais"
  - name: srcsubpath
    value: oldrag
  - name: repo_dockerhub
    value:
  - name: registry
    value: "PercapitaDockerImages"
  - name: GITID
    value: $(Build.SourceVersion)
  - name: is_release
    value: false
  - name: dockertags
    value: 'latest'

steps:
  - bash: |
      set -eux
      pwd
      ls -la
      echo "$(Build.SourceVersion)" > version.tmp
      echo "version.tmp contents:"
      cat version.tmp
      echo "tags=$(dockertags)"
    displayName: "Create version.tmp"
    workingDirectory: "$(System.DefaultWorkingDirectory)/$(srcsubpath)"

  - task: Docker@2
    displayName: "Login to registry: $(registry)"
    inputs:
      command: login
      containerRegistry: $(registry)

  - task: Docker@2
    displayName: "docker build"
    inputs:
      repository: $(docker_aiservice_repo)
      command: build
      buildContext: "$(System.DefaultWorkingDirectory)/$(srcsubpath)"
      Dockerfile: "$(System.DefaultWorkingDirectory)/$(srcsubpath)/Dockerfile"
      tags: |
        $(dockertags)

  - task: Docker@2
    displayName: "docker push"
    inputs:
      repository: $(docker_aiservice_repo)
      command: push
      buildContext: "$(System.DefaultWorkingDirectory)/$(srcsubpath)"
      Dockerfile: "$(System.DefaultWorkingDirectory)/$(srcsubpath)/Dockerfile"
      tags: |
        $(dockertags)